version: '3.7'
services:
  docker-flask:
      container_name: ''
      build: .
      image: mohdazharkhan/docker-flask
      volumes:
        - .:/usr/src/app
        - $HOME/.aws:/root/.aws
      ports:
        - "5000"
      tty: true
      env_file:
        - .env
      healthcheck:
        test: curl --fail http://localhost:5000/health
        interval: 30s
        timeout: 5s
        retries: 2
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 50M
          reservations:
            cpus: '0.25'
            memory: 20M
        replicas: 2
        restart_policy:
          condition: any
          delay: 5s
          window: 120s
        update_config:
          parallelism: 1
          delay: 10s
          order: start-first
