version: '3'
services:
  docker-flask:
      container_name: ''
      build: .
      image: mohdazharkhan/docker-flask
      volumes:
        - .:/usr/src/app
        - $HOME/.aws:/root/.aws
      ports:
        - "5000:5000"
      tty: true
      env_file:
        - .env
