version: '3'
services:
  docker-flask:
      container_name: ''
      build: .
      image: mohdazharkhan/docker-flask
      volumes:
        - .:/usr/src/app
        - $HOME/.aws:/root/.aws
      ports:
        - "5000:5000"
      tty: true
      env_file:
        - .env
      healthcheck:
        test: curl --fail http://localhost:5000/health
        interval: 30s
        timeout: 5s
        retries: 2
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 50M
          reservations:
            cpus: '0.25'
            memory: 20M
  
