version: '3'
services:
  docker-flask:
      container_name: docker-flask
      build: .
      volumes:
        - .:/usr/src/app
        - $HOME/.aws:/root/.aws
      ports:
        - "5000:5000"
      tty: true
      env_file:
        - .env
